name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["type:bug"]
body:
- type: textarea
id: steps
attributes:
label: Steps to reproduce
placeholder: "1. Go to...\n2. Click...\n3. See error"
validations:
required: true
- type: textarea
id: expected
attributes:
label: Expected behavior
validations:
required: true
- type: textarea
id: actual
attributes:
label: Actual behavior / screenshots
- type: input
id: env
attributes:
label: Environment
placeholder: "OS, Browser, Version"
- type: checkboxes
id: regression
attributes:
label: Regression?
options:
- label: This used to work before